Remove recursive_defaults from the get_config arg
Do not use 'recursive_defaults' as argument of the funciton get_config()
It cause vyos-1x/src/tests/test_configd_inspect.py signature checks fail

AssertionError: 2 != 1 : 'vpp_interfaces_bonding.py': 'get_config' incorrect signature